version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
      target: builder
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - .:/app
      - ${PROJECT_NAME}-venv-volume-${ENV}:/app/.venv
    command: bash -c 'poetry install --no-root && poetry run python manage.py runserver 0.0.0.0:8000'

volumes:
  ${PROJECT_NAME}-venv-volume-${ENV}:
  ${PROJECT_NAME}-static-volume-${ENV}:
