services:
  nginx:
    ports: !override
      - "${HOST_BIND_IP}:${DEV_PORT}:80"

  web:
    build:
      target: development
    env_file:
      - .env
    environment:
      - DEBUG=True
      - POSTGRES_DB=${POSTGRES_DEV_DB}
    volumes:
      - .:/app
      - /app/.venv

  db:
    environment:
      - POSTGRES_DB=${POSTGRES_DEV_DB}
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DEV_DB}" ]

volumes:
  postgres-db:
    driver: local
    name: ${PROJECT_NAME}-postgres-db-dev
    external: false
