name: Run Docker Tests

on:
  workflow_call:

jobs:
  run-docker-tests:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        test_target: [build-test, pstg-test, e2e-test]
    steps:
      - uses: ./.github/actions/setup-test-env

      - name: Run ${{ matrix.test_target }}
        env:
          SUDO: ${{ secrets.SUDO || 'true' }}
        run: make ${{ matrix.test_target }}