name: Run Local Tests

on:
  workflow_call:

jobs:
  run-local-tests:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        test_target: [unit-test, sqlt-test, intg-test]
    steps:
      - uses: ./.github/actions/setup/test.yml

      - name: Run ${{ matrix.test_target }}
        run: make ${{ matrix.test_target }}