name: Run Tests

on:
  workflow_call:

jobs:
  run-tests:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        test_target: [unit-test, db-test, build-test, e2e-test]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version-file: .python-version

      - name: Install and configure Poetry
        run: |
          pipx install poetry
          poetry config virtualenvs.in-project true
          echo "$HOME/.local/bin" >> $GITHUB_PATH

      - name: Install dependencies
        run: make setup

      - name: Run tests
        env:
          DJANGO_SETTINGS_MODULE: config.settings
          DJANGO_SECRET_KEY: ${{ secrets.DJANGO_SECRET_KEY || 'test-secret-key' }}
          DATABASE_URL: ${{ secrets.DATABASE_URL || 'postgres://user:pass@localhost:5432/testdb' }}
          DJANGO_ENV: test
          # The following variables are for docker-compose, but we set them here for consistency.
          DB_NAME: ${{ secrets.DB_NAME || 'testdb' }}
          DB_USER: ${{ secrets.DB_USER || 'user' }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD || 'pass' }}
          HOST_BIND_IP: "127.0.0.1"
          HOST_PORT: "8000"
        run: make ${{ matrix.test_target }}
