name: Run Tests

on:
  workflow_call:

jobs:
  run-tests:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - test_type: "local"
            targets: ["unit-test", "sqlt-test", "intg-test"]
          - test_type: "docker"
            targets: ["build-test", "pstg-test", "e2e-test"]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version-file: .python-version

      - name: Install uv
        run: pipx install uv

      - name: Install dependencies
        run: uv sync --frozen

      - name: Create .env file for CI
        run: cp .env.example .env

      - name: Run ${{ matrix.test_type }} tests
        env:
          SUDO: ${{ secrets.SUDO || 'true' }}
        run: |
          for target in ${{ join(matrix.targets, ' ') }}; do
            echo "Running: make $target"
            make $target
          done
